### ISSUE TITLE
pyproject.toml [tool.pdm.venv] is ignored?

### ISSUE THREAD

**Issue by mgzenitech** [pdm-project/pdm-venv#42]
**Describe the bug**
Basically I have added section to **pyproject.toml** file (not **.pdm.toml**):

```toml
[tool.pdm.venv]
in_project = true
```

**To Reproduce**
```shell
pdm install
```

**Expected behavior**
venv is created in project directory.
